[package]
name        = "exp-cfg-test"
version     = "0.1.1"
edition     = "2021"
authors     = ["kanarus <kanarus786@gmail.com>"]
repository  = "https://github.com/kanarus/exp-cfg-test"
license     = "MIT"
description = "experiment of exporting code behind #[cfg(test)]"